FROM openjdk:8-jdk-alpine
MAINTAINER FuFei
WORKDIR /runtime
COPY ds-server-*.jar app.jar

ENV ACTIVE=""
ENV TZ=Asia/Shanghai

RUN echo "http://mirrors.aliyun.com/alpine/v3.8/main/" > /etc/apk/repositories
RUN echo "http://mirrors.aliyun.com/alpine/v3.8/community/" >> /etc/apk/repositories
RUN apk update
RUN apk add --no-cache tini bash tzdata
RUN apk add --no-cache openssl wget ca-certificates
RUN apk add --no-cache ttf-dejavu fontconfig && rm -rf /var/cache/apk/*
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ["tini", "--", "java", "-Dspring.profiles.active=${ACTIVE}", "-jar", "/runtime/app.jar"]